name: Reusable workflow

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true


env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/bigid-dmyh"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    name: lint_and_test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python_version }}"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python linter and comment PR
        if: github.event_name == 'pull_request'
        uses: matias-martini/flake8-pr-comments-action@main
        with:
          github_token: ${{ github.token }}
          plugins: "flake8-functions"
      - name: Run Python linter on push
        if: github.event_name == 'push'
        run: |
              flake8 .
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          failure-threshold: warning

      - name: Run tests with pytest
        run: pytest
      - name: Build an image from Dockerfile
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          scanners: 'vuln,secret'
          vuln-type: 'os,library'
          #severity: 'MEDIUM,CRITICAL,HIGH'
          severity: 'CRITICAL,HIGH'