
name: Lint and Test

on: [pull_request]

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/bigid-dmyh"

jobs:
  lint_and_test:
    name: Lint and Test
    uses: ./.github/workflows/build-and-push.yml
    with:
      python-version: "3.12"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

