name: PR

on: [pull_request]

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/bigid-dmyh"

jobs:
  Lint_and_Test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run linter and comment PR
        uses: matias-martini/flake8-pr-comments-action@main
        with:
          github_token: ${{ github.token }}
          plugins: "flake8-functions"
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          failure-threshold: warning
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
      - name: Build an image from Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          # Do not push to registry in this step
          push: false
          # Define the image tag
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          # Export the image as a tar file
          outputs: type=docker,dest=/tmp/app-image.tar
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          scanners: 'vuln,secret'
          vuln-type: 'os,library'
          #severity: 'MEDIUM,CRITICAL,HIGH'
          severity: 'CRITICAL,HIGH'
      # Upload the tar file as a workflow artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: /tmp/app-image.tar

