
name: Lint and Test

on: [pull_request]

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/bigid-dmyh"

jobs:
  lint_and_test:
    permissions:
      pull-requests: write
    name: Lint and Test
    uses: ./.github/workflows/lint-and-test.yml
    with:
      python_version: "3.12"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

