name: test-build-deploy

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/bigid-dmyh"

jobs:
  lint_and_test:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/lint-and-test.yml
    with:
      python-version: "3.12"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  build_push:
    needs: lint_and_test
    name: Build, Push, Deploy
    runs-on: ubuntu-latest
    steps:
      # Log in to Docker Hub using stored secrets
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Push the loaded image to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
